/* https://www.scifiideas.com/sci-fi-character-name-generator/ */

module.exports = [
	'Ke\'kloren Royzok',
	'Be\'alvak Queebklep',
	'Va\'hop Bobbongtissi',
	'Kzoik Quern',
	'Grozo Borokklep',
	'Metagon Loturian',
	'The Ancient Kruts of Knedania',
	'Vrokjo Globzon',
	'Kbian Honronorn',
	'Gcut Baxkooaico',
	'Klagong Taclanzula',
	'The Ancient Juralvak of Vengatis',
	'Topzon Olkzodblob',
	'The Ancient Andzop of Poolaka',
	'High Ambassador Chlit',
	'Squnol Dudeks',
	'Caktin Topeks',
	'Cachut Straalbag',
	'Jadahop Klumoln',
	'Judkro Jadaeux',
	'Tomzut Olgjar',
	'Klumcut Honurian',
	'Vodons Grojed',
	'Kjed Bobgon',
	'Kaysor Krlorm',
	'Volzad Arclily',
	'Ferbon Dinzed',
	'Keux Queeberdjos',
	'Roynir Helaik',
	'The Ancient Mobzuc of Eavis',
	'Kackzulu Nelhut',
	'Gobgongon Ba\'jos',
	'The High Gurjud of Zemtania',
	'Zomklep Tacargzut',
	'Colonel Grelobb',
	'The Great Zomkro of Anlas',
	'Gebzula Squbon',
	'Jadazad Baxbong',
	'Adrlinn Catlinnlily',
	'Moncit Klaurian',
	'Dopjan Tedaveola',
	'B\'oria Heltet',
	'Caczell Bineillit',
	'Vophop Binebag',
	'Kackhop Hobcer',
	'Molite Bolgongon',
	'Bolflen Grogogo',
	'Groain Blibjidgong',
	'Vopzulu Olkerd',
	'Luralg Klupot',
	'Judro Borro',
	'Olkcat Sudaog',
	'Katjed Squnir',
	'Arclinn Vodzod',
	'Squegs Tadturianblag',
	'Dinbon Straeux',
	'Fersloff Chgan',
	'Bopeax Tamaico',
	'Bopnir B\'gogosor',
	'Kackgun Adrtor',
	'Blite Gutthut',
	'Mesabag Nirflomnol',
	'Zomed Ched',
	'Charles Bloodspeeder',
	'Anmolpreet Beard',
	'Hogan Jadell',
	'Officer Killy Emberburton',
	'Kalister Pulan',
	'Ridley Sostov',
	'Jarell Kelcaster',
	'Dale Hall',
	'Professor Ewing Langley',
	'Major Isira Stanson',
	'Lt Tandra Coffey',
	'Krames Feyoun',
	'Quarl Martell Snr',
	'Ilyas Justice',
	'Gabriel Bumenter',
	'Srzia Higher',
	'Hamzah Jacobson Snr',
	'Tuben Walter',
	'Quon Wley',
	'Nohn Dodchair Snr',
	'Dre Ghostscooter',
	'SCPO Cadyn Kline III',
	'Shergo Spectrumspeeder',
	'Kaan Phaseratus',
	'Sohn Smithnighter',
	'Callun Corey-Jay Sexton',
	'Patrick Swordton III',
	'Harvey Embsaberer',
	'Jaxon Zell',
	'Johnathan Rutledge Snr',
	'Alvern Watkins',
	'Aarman Ikechukwu Wox',
	'Daragh Bradshaw',
	'Samuel Kroan',
	'Lochlann Scanspeeder',
	'Sex Burflyer',
	'Jahid Bretmer Jr.',
	'Raheem Farrell',
	'Sohn Berger',
	'Jasim Spectrumaite',
	'Zalister Vulan',
	'Brick Bellis',
	'Jadiki Mcspeeder',
	'Deon Aref Dall',
	'Macaulay Solfist the 2nd',
	'Casper Spinworth',
	'Kamil Irley',
	'Abdullah Horton',
	'Dolim Pell',
	'Marzuq Graham II',
	'Ross-Andrew Holden',
	'Aryn Kaufman',
	'Brerry Day',
	'Lt Cmdr Srzee O\'caster',
	'Minister Voey Hartman II',
	'Wrarl Spellis',
	'Donnie Shields',
	'Aedyn Hursor',
	'Conghaile Priker',
	'Krishan Embworm',
	'Selen Colotov',
	'Welen Jadark the 2nd',
	'Joseph Erickson',
	'Lt Fizzy Curry',
	'Jaxson Dreamett',
	'Conli Coel Roberson',
	'Allesandro Morales',
	'Cizzy Delaney',
	'Prex Austin',
	'Kecca Knowles Ph.D',
	'Amani Pursor BSc',
	'Santino Tomm',
	'Maxwell Nursor',
	'Sroey Mcher',
	'Lt Sex Turner',
	'Ayren Cell',
	'Dhani Kyhran Nogawa',
	'Cavan Green',
	'Fake Tyler the 2nd',
	'Fearghus Wolfe',
	'Conlin Salazar Sr.',
	'Shaun-Paul Blacksailer',
	'Stark Lightisomb',
	'Stilly Berry',
	'Mario Diaz',
	'Brandra Pedex the 2nd',
	'Darrius Solotov',
	'Antonio Elliott',
	'Garren Stephenson',
	'Dan Sampson',
	'Rylan Fionn Dideman',
	'AJ Leonard',
	'Bryden Irich',
];